version: '3.7'
services:
  db:
    container_name: 'tripulante'
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: backendtripulante
      POSTGRES_DB: backendtripulante
      POSTGRES_PASSWORD: backendtripulante
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: